Nei - Neanderthal funker ikke (ut av boksen) på Application.Garden.
Application.Garden sa stopp ved :require av uncomplicate.neanderthal.native. Man
kan gjette at det mangler native-bindings for sånn ting kjører på
Application.Garden. Det er mulig dette kan fikses ved å legge til flere
avhengigheter, kommentarblokker hinter til at man må få med intel-mkl.

Motivasjonen er uansett uklar for å kjøre tallknusing på Application.Garden -
plattformen er (for nå) laget for å svare kjapt på HTTP-spørringer, ikke til å
stå og kverne på vanskelige numeriske problemer.

Her er hele feilmeldingen:

    Pushing code to garden...
    Starting new deployment...
    Downloading: net/minidev/json-smart/maven-metadata.xml from central
    Fetched dependencies
    Started nREPL server on 0.0.0.0:6666
    SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
    SLF4J: Defaulting to no-operation (NOP) logger implementation
    SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
    {:clojure.main/message
     "Execution error (ClassNotFoundException) at jdk.internal.loader.BuiltinClassLoader/loadClass (BuiltinClassLoader.java:641).\nclojure.pprint$fn__10945$fn__10948\n",
     :clojure.main/triage
     {:clojure.error/class java.lang.ClassNotFoundException,
      :clojure.error/line 641,
      :clojure.error/cause "clojure.pprint$fn__10945$fn__10948",
      :clojure.error/symbol
      jdk.internal.loader.BuiltinClassLoader/loadClass,
      :clojure.error/source "BuiltinClassLoader.java",
      :clojure.error/phase :execution},
     :clojure.main/trace
     {:via
      [{:type clojure.lang.Compiler$CompilerException,
        :message
        "Syntax error macroexpanding at (uncomplicate/neanderthal/native.clj:1:1).",
        :data
        {:clojure.error/phase :execution,
         :clojure.error/line 1,
         :clojure.error/column 1,
         :clojure.error/source "uncomplicate/neanderthal/native.clj"},
        :at [clojure.lang.Compiler load "Compiler.java" 8177]}
       {:type java.lang.ExceptionInInitializerError,
        :at [uncomplicate.neanderthal.internal.printing__init load nil 30]}
       {:type java.lang.ClassNotFoundException,
        :message "clojure.pprint$fn__10945$fn__10948",
        :at
        [jdk.internal.loader.BuiltinClassLoader
         loadClass
         "BuiltinClassLoader.java"
         641]}],
      :trace
      [[jdk.internal.loader.BuiltinClassLoader
        loadClass
        "BuiltinClassLoader.java"
        641]
       [jdk.internal.loader.ClassLoaders$AppClassLoader
        loadClass
        "ClassLoaders.java"
        188]
       [java.lang.ClassLoader loadClass "ClassLoader.java" 526]
       [java.lang.Class forName0 "Class.java" -2]
       [java.lang.Class forName "Class.java" 534]
       [java.lang.Class forName "Class.java" 513]
       [clojure.lang.RT classForName "RT.java" 2229]
       [clojure.lang.RT classForName "RT.java" 2238]
       [clojure.lang.LispReader$EvalReader invoke "LispReader.java" 1320]
       [clojure.lang.LispReader$DispatchReader
        invoke
        "LispReader.java"
        861]
       [clojure.lang.LispReader read "LispReader.java" 287]
       [clojure.lang.LispReader read "LispReader.java" 218]
       [clojure.lang.LispReader read "LispReader.java" 207]
       [clojure.lang.RT readString "RT.java" 1896]
       [clojure.lang.RT readString "RT.java" 1891]
       [uncomplicate.neanderthal.internal.printing$fn__15160
        <clinit>
        "printing.clj"
        32]
       [uncomplicate.neanderthal.internal.printing__init load nil 30]
       [uncomplicate.neanderthal.internal.printing__init <clinit> nil -1]
       [java.lang.Class forName0 "Class.java" -2]
       [java.lang.Class forName "Class.java" 534]
       [java.lang.Class forName "Class.java" 513]
       [clojure.lang.RT classForName "RT.java" 2229]
       [clojure.lang.RT classForName "RT.java" 2238]
       [clojure.lang.RT loadClassForName "RT.java" 2257]
       [clojure.lang.RT load "RT.java" 469]
       [clojure.lang.RT load "RT.java" 444]
       [clojure.core$load$fn__6931 invoke "core.clj" 6189]
       [clojure.core$load invokeStatic "core.clj" 6188]
       [clojure.core$load doInvoke "core.clj" 6172]
       [clojure.lang.RestFn invoke "RestFn.java" 411]
       [clojure.core$load_one invokeStatic "core.clj" 5961]
       [clojure.core$load_one invoke "core.clj" 5956]
       [clojure.core$load_lib$fn__6873 invoke "core.clj" 6003]
       [clojure.core$load_lib invokeStatic "core.clj" 6002]
       [clojure.core$load_lib doInvoke "core.clj" 5981]
       [clojure.lang.RestFn applyTo "RestFn.java" 145]
       [clojure.core$apply invokeStatic "core.clj" 669]
       [clojure.core$load_libs invokeStatic "core.clj" 6048]
       [clojure.core$load_libs doInvoke "core.clj" 6028]
       [clojure.lang.RestFn applyTo "RestFn.java" 140]
       [clojure.core$apply invokeStatic "core.clj" 669]
       [clojure.core$require invokeStatic "core.clj" 6066]
       [uncomplicate.neanderthal.internal.cpp.structures$loading__6814__auto____169
        invoke
        "structures.clj"
        9]
       [uncomplicate.neanderthal.internal.cpp.structures__init load nil 9]
       [uncomplicate.neanderthal.internal.cpp.structures__init
        <clinit>
        nil
        -1]
       [java.lang.Class forName0 "Class.java" -2]
       [java.lang.Class forName "Class.java" 534]
       [java.lang.Class forName "Class.java" 513]
       [clojure.lang.RT classForName "RT.java" 2229]
       [clojure.lang.RT classForName "RT.java" 2238]
       [clojure.lang.RT loadClassForName "RT.java" 2257]
       [clojure.lang.RT load "RT.java" 469]
       [clojure.lang.RT load "RT.java" 444]
       [clojure.core$load$fn__6931 invoke "core.clj" 6189]
       [clojure.core$load invokeStatic "core.clj" 6188]
       [clojure.core$load doInvoke "core.clj" 6172]
       [clojure.lang.RestFn invoke "RestFn.java" 411]
       [clojure.core$load_one invokeStatic "core.clj" 5961]
       [clojure.core$load_one invoke "core.clj" 5956]
       [clojure.core$load_lib$fn__6873 invoke "core.clj" 6003]
       [clojure.core$load_lib invokeStatic "core.clj" 6002]
       [clojure.core$load_lib doInvoke "core.clj" 5981]
       [clojure.lang.RestFn applyTo "RestFn.java" 145]
       [clojure.core$apply invokeStatic "core.clj" 669]
       [clojure.core$load_libs invokeStatic "core.clj" 6044]
       [clojure.core$load_libs doInvoke "core.clj" 6028]
       [clojure.lang.RestFn applyTo "RestFn.java" 140]
       [clojure.core$apply invokeStatic "core.clj" 669]
       [clojure.core$require invokeStatic "core.clj" 6066]
       [clojure.core$require doInvoke "core.clj" 6066]
       [clojure.lang.RestFn invoke "RestFn.java" 485]
       [uncomplicate.neanderthal.native$eval21808$loading__6812__auto____21809
        invoke
        "native.clj"
        9]
       [uncomplicate.neanderthal.native$eval21808
        invokeStatic
        "native.clj"
        9]
       [uncomplicate.neanderthal.native$eval21808 invoke "native.clj" 9]
       [clojure.lang.Compiler eval "Compiler.java" 7700]
       [clojure.lang.Compiler eval "Compiler.java" 7689]
       [clojure.lang.Compiler load "Compiler.java" 8165]
       [clojure.lang.RT loadResourceScript "RT.java" 401]
       [clojure.lang.RT loadResourceScript "RT.java" 392]
       [clojure.lang.RT load "RT.java" 479]
       [clojure.lang.RT load "RT.java" 444]
       [clojure.core$load$fn__6931 invoke "core.clj" 6189]
       [clojure.core$load invokeStatic "core.clj" 6188]
       [clojure.core$load doInvoke "core.clj" 6172]
       [clojure.lang.RestFn invoke "RestFn.java" 411]
       [clojure.core$load_one invokeStatic "core.clj" 5961]
       [clojure.core$load_one invoke "core.clj" 5956]
       [clojure.core$load_lib$fn__6873 invoke "core.clj" 6003]
       [clojure.core$load_lib invokeStatic "core.clj" 6002]
       [clojure.core$load_lib doInvoke "core.clj" 5981]
       [clojure.lang.RestFn applyTo "RestFn.java" 145]
       [clojure.core$apply invokeStatic "core.clj" 669]
       [clojure.core$load_libs invokeStatic "core.clj" 6048]
       [clojure.core$load_libs doInvoke "core.clj" 6028]
       [clojure.lang.RestFn applyTo "RestFn.java" 140]
       [clojure.core$apply invokeStatic "core.clj" 669]
       [clojure.core$require invokeStatic "core.clj" 6066]
       [clojure.core$require doInvoke "core.clj" 6066]
       [clojure.lang.RestFn invoke "RestFn.java" 424]
       [go.linalg$eval21802 invokeStatic "linalg.clj" 18]
       [go.linalg$eval21802 invoke "linalg.clj" 18]
       [clojure.lang.Compiler eval "Compiler.java" 7700]
       [clojure.lang.Compiler load "Compiler.java" 8165]
       [clojure.lang.RT loadResourceScript "RT.java" 401]
       [clojure.lang.RT loadResourceScript "RT.java" 392]
       [clojure.lang.RT load "RT.java" 479]
       [clojure.lang.RT load "RT.java" 444]
       [clojure.core$load$fn__6931 invoke "core.clj" 6189]
       [clojure.core$load invokeStatic "core.clj" 6188]
       [clojure.core$load doInvoke "core.clj" 6172]
       [clojure.lang.RestFn invoke "RestFn.java" 411]
       [clojure.core$load_one invokeStatic "core.clj" 5961]
       [clojure.core$load_one invoke "core.clj" 5956]
       [clojure.core$load_lib$fn__6873 invoke "core.clj" 6003]
       [clojure.core$load_lib invokeStatic "core.clj" 6002]
       [clojure.core$load_lib doInvoke "core.clj" 5981]
       [clojure.lang.RestFn applyTo "RestFn.java" 145]
       [clojure.core$apply invokeStatic "core.clj" 669]
       [clojure.core$load_libs invokeStatic "core.clj" 6044]
       [clojure.core$load_libs doInvoke "core.clj" 6028]
       [clojure.lang.RestFn applyTo "RestFn.java" 140]
       [clojure.core$apply invokeStatic "core.clj" 669]
       [clojure.core$require invokeStatic "core.clj" 6066]
       [clojure.core$require doInvoke "core.clj" 6066]
       [clojure.lang.RestFn invoke "RestFn.java" 515]
       [go.core$eval20125 invokeStatic "core.clj" 241]
       [go.core$eval20125 invoke "core.clj" 241]
       [clojure.lang.Compiler eval "Compiler.java" 7700]
       [clojure.lang.Compiler load "Compiler.java" 8165]
       [clojure.lang.RT loadResourceScript "RT.java" 401]
       [clojure.lang.RT loadResourceScript "RT.java" 392]
       [clojure.lang.RT load "RT.java" 479]
       [clojure.lang.RT load "RT.java" 444]
       [clojure.core$load$fn__6931 invoke "core.clj" 6189]
       [clojure.core$load invokeStatic "core.clj" 6188]
       [clojure.core$load doInvoke "core.clj" 6172]
       [clojure.lang.RestFn invoke "RestFn.java" 411]
       [clojure.core$load_one invokeStatic "core.clj" 5961]
       [clojure.core$load_one invoke "core.clj" 5956]
       [clojure.core$load_lib$fn__6873 invoke "core.clj" 6003]
       [clojure.core$load_lib invokeStatic "core.clj" 6002]
       [clojure.core$load_lib doInvoke "core.clj" 5981]
       [clojure.lang.RestFn applyTo "RestFn.java" 145]
       [clojure.core$apply invokeStatic "core.clj" 669]
       [clojure.core$load_libs invokeStatic "core.clj" 6044]
       [clojure.core$load_libs doInvoke "core.clj" 6028]
       [clojure.lang.RestFn applyTo "RestFn.java" 140]
       [clojure.core$apply invokeStatic "core.clj" 669]
       [clojure.core$require invokeStatic "core.clj" 6066]
       [clojure.core$require doInvoke "core.clj" 6066]
       [clojure.lang.RestFn applyTo "RestFn.java" 140]
       [clojure.core$apply invokeStatic "core.clj" 667]
       [clojure.core$serialized_require invokeStatic "core.clj" 6142]
       [clojure.core$requiring_resolve invokeStatic "core.clj" 6151]
       [clojure.core$requiring_resolve invoke "core.clj" 6145]
       [nextjournal.garden_nrepl$start_app_BANG_
        invokeStatic
        "garden_nrepl.clj"
        13]
       [nextjournal.garden_nrepl$start_app_BANG_
        invoke
        "garden_nrepl.clj"
        9]
       [nextjournal.garden_nrepl$start_BANG_
        invokeStatic
        "garden_nrepl.clj"
        27]
       [nextjournal.garden_nrepl$start_BANG_ invoke "garden_nrepl.clj" 25]
       [clojure.lang.Var invoke "Var.java" 386]
       [clojure.run.exec$exec invokeStatic "exec.clj" 88]
       [clojure.run.exec$exec invoke "exec.clj" 78]
       [clojure.run.exec$_main$fn__229 invoke "exec.clj" 227]
       [clojure.run.exec$_main invokeStatic "exec.clj" 223]
       [clojure.run.exec$_main doInvoke "exec.clj" 191]
       [clojure.lang.RestFn applyTo "RestFn.java" 140]
       [clojure.lang.Var applyTo "Var.java" 707]
       [clojure.core$apply invokeStatic "core.clj" 667]
       [clojure.main$main_opt invokeStatic "main.clj" 515]
       [clojure.main$main_opt invoke "main.clj" 511]
       [clojure.main$main invokeStatic "main.clj" 665]
       [clojure.main$main doInvoke "main.clj" 617]
       [clojure.lang.RestFn applyTo "RestFn.java" 140]
       [clojure.lang.Var applyTo "Var.java" 707]
       [clojure.main main "main.java" 40]],
      :cause "clojure.pprint$fn__10945$fn__10948",
      :phase :execution}}

    Execution error (ClassNotFoundException) at jdk.internal.loader.BuiltinClassLoader/loadClass (BuiltinClassLoader.java:641).
    clojure.pprint$fn__10945$fn__10948

    [Deploying... |]
    ERROR: your project could not be started.